### PR TITLE
Use fewer macros without losing performance

### PR DESCRIPTION
**Pull request by reem**
More types, fewer macros! No performance loss!

If you're wondering about the flurry of PRs it's because I'm about
to fork this code to work with @cgaebel's iobuf library, so I'm
just making some changes before I get started.

### CODE REVIEW

**Comment by reem** [comment]
err, wait, don't merge this, I made this PR to hastily

**Comment by reem** [comment]
@seanmonstar should be ready to go now

**Comment by seanmonstar** [comment]
Tests errored.

Curious, why inline functions over macros?

**Comment by reem** [comment]
Typo, fixed it.

Functions are clearer than macros imo when you don't need macro features like return from caller.

**Pull request merged**
