### PR TITLE
Trailing whitespace

### PR DESCRIPTION
**Pull request by lpbak**
Proposed fix for issue #15.

### CODE REVIEW

**Comment by seanmonstar** [comment]
Neat! Do you know what the difference is with the benchmark?

**Comment by lpbak** [comment]
I've run this change against the benchmark (after dealing with #27) and unfortunately, the impact seems to be significant. I'll try to look into it further.

**Comment by lpbak** [comment]
I've been able to decrease benchmark times somewhat, but the impact of this change is still visible. Please, decide whether this impact is acceptable, and act on this PR accordingly.

**Comment by seanmonstar** [comment]
I'm sorry, not ignoring, I'll look into the benchmarks in the next couple days.

**Comment by seanmonstar** [comment]
I just tried this out, and on my machine, I see almost a 157% increase in parse time (638ns vs 1006ns), which is probably too much.  Additionally, I expect client and servers to selectively only trim header values that need to be trimmed. Considering that trimming all header values is not necessarily something that needs to be done, it feels too expensive.

If we could keep the performance cost much much lower, it may be worth it. Thanks @lpbak for trying this out!

**Pull request closed without merging**
