### PR TITLE
Uninit headers - second approach

### PR DESCRIPTION
**Pull request by Soveu**
Previous attempt: #97 
Fixes: #95 and #58

### CODE REVIEW

**Comment by Soveu** [comment]
@seanmonstar do we consider bumping minimal rustc version, like in `hyper`? Looks like CI is failing (mainly) because of no `MaybeUninit`

**Comment by Soveu** [comment]
@seanmonstar ?

**Comment by RalfJung** [comment]
> Looks like CI is failing (mainly) because of no MaybeUninit in 1.10

https://crates.io/crates/maybe-uninit would let you support at least Rust 1.20 while ensuring soundness on Rust 1.36+.

Even older versions of Rust do not really have any good way to work with uninit data correctly. If they still need to be supported, possibly a feature flag could be used to provide this API only when the user asks for it? I will note though that Rust 1.20 is already ancient, it was released 4 years ago.

**Comment by seanmonstar** [comment]
Ok, let's work on this! First thing I did was get CI moved from Travis to GH Actions.

For MSRV, it's probably fine we just bump it to 1.36. It's two years old at this point!

**Comment by Soveu** [comment]
A force-pushed empty commit would restart CI?

**Comment by seanmonstar** [comment]
Hm, probably a rebase of master.

**Comment by Soveu** [comment]
ugh, sorry for the wait, git didn't want to cooperate with me -_-

**Comment by seanmonstar** [comment]
Yea, so the new CI is failing the msrv job. You can just update the yaml file to set the new MSRV.

**Review by seanmonstar — APPROVED** [review]

**Pull request merged**
