### PR TITLE
Add no_std feature, impl std::error::Error

### PR DESCRIPTION
**Pull request by abonander**

### CODE REVIEW

**Comment by abonander** [comment]
@seanmonstar Are you waiting to publish a new version or did you forget again? ;P

**Comment by seanmonstar** [comment]
Something tickles me weird about having the `no_std` be a feature. I wanted to think about it some to see if there's something better.

**Comment by abonander** [comment]
It's a common convention, I made it a default so it didn't break any existing usage expecting it to work with `core` right out of the box.

**Comment by abonander** [comment]
@seanmonstar Would you prefer to leave the `#![no_std]` unconditional and just have a `std` feature? I think that would work:

    #![no_std] 

    #[cfg(feature = "std")]
    extern crate std;

    #[cfg(feature = "std")]
    impl ::std::error::Error for Error { /* ... */ }

**Comment by seanmonstar** [comment]
Ignore me, it's perfect. Thanks!

**Comment by jethrogb** [comment]
The convention is to have a feature named `std`, see [this comment](https://github.com/rust-lang-nursery/rand/pull/108#issuecomment-231556510) for rationale.

**Comment by seanmonstar** [comment]
@jethrogb so, have this instead:

```toml
[features]
default = ["std"]
std = []
```

And anyone wanting to use it in a `no_std` environment sets `default-features = false`.

**Comment by seanmonstar** [comment]
If that seems correct, I've made a PR to do that, and I can release the new version today https://github.com/seanmonstar/httparse/pull/23

**Pull request merged**
