### PR TITLE
Added header function to extract specific value

### PR DESCRIPTION
**Pull request by hanscj1**
Added a function that supports UniCase and extracts the specific value for a given header.

### CODE REVIEW

**Comment by seanmonstar** [comment]
Thanks for the pull request!

Is there a reason to include this in this crate, instead of just implementing this where one needs it? An issue I see here is that the unicase crate needs std, and httparse tries to work without it.

**Comment by hanscj1** [comment]
I'll take a look at doing that in my library. It was just easier at the time. thx

**Comment by hanscj1** [comment]
Just curious, I have seen several libraries lately working toward !std, why? thx

**Comment by seanmonstar** [comment]
I don't have any special interest in bending over backwards to make it work with `no_std`, but httparse just didn't need anything in `std`. The benefit is that people can use those libraries on small hardware, where executable size may be important, or access to a heap may not even exist.

**Pull request closed without merging**
